# Generated by Django 3.2.16 on 2022-11-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='back_check_img',
            field=models.ImageField(default=0, upload_to='back_check_pics'),
            preserve_default=False,
        ),
    ]
